In [1]:
USE {
    dependencies("org.mariadb.jdbc:mariadb-java-client:3.5.4")
}

In [3]:
%useLatestDescriptors
%use dataframe(1.0.0-dev-10213)

In [2]:
import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.api.describe
import org.jetbrains.kotlinx.dataframe.api.print
import org.jetbrains.kotlinx.dataframe.io.DbConnectionConfig
import org.jetbrains.kotlinx.dataframe.io.readDataFrameSchema
import org.jetbrains.kotlinx.dataframe.io.readSqlTable
import org.jetbrains.kotlinx.dataframe.io.readDataFrame
import org.jetbrains.kotlinx.dataframe.schema.DataFrameSchema
import org.jetbrains.kotlinx.dataframe.examples.jdbc.*
import java.sql.DriverManager
import java.util.*

**The IMDB Database Exploration: printing schemas for all non-system tables**

To run these examples, you need to install the MariaDB database server and load the dump into a database. Read more in the [Readme.md](https://github.com/zaleslaw/KotlinDataFrame-SQL-Examples/blob/master/Readme.md).

In [4]:
val dbConfig = DbConnectionConfig(URL, USER_NAME, PASSWORD)

val dataschemas = DataFrameSchema.readAllSqlTables(dbConfig)

dataschemas.forEach {
    println("--- Schema for Table ${it.key} ---")
    println(it.value)
    println()
}

kotlin-logging: initializing... active logger factory: Slf4jLoggerFactory
--- Schema for Table actors ---
id: Int
first_name: String?
last_name: String?
gender: String?

--- Schema for Table directors ---
id: Int
first_name: String?
last_name: String?

--- Schema for Table directors_genres ---
director_id: Int
genre: String
prob: Float?

--- Schema for Table movies ---
id: Int
name: String?
year: Int?
rank: Float?

--- Schema for Table movies_directors ---
director_id: Int
movie_id: Int

--- Schema for Table movies_genres ---
movie_id: Int
genre: String

--- Schema for Table roles ---
actor_id: Int
movie_id: Int
role: String

**The IMDB Data Quick Exploration: printing 100 rows from each non-system table**

In [5]:
import org.jetbrains.kotlinx.dataframe.io.readAllSqlTables

val dfs = DataFrame.readAllSqlTables(dbConfig, limit = 100).values

dfs.forEach {
    it.describe().print()
    it.print(5)
}

         name   type count unique nulls     top freq  mean       std         min     p25  median     p75         max
 0         id    Int   100    100     0       2    1 53,37 30,245679           2      26      54      80         106
 1 first_name String   100     93     0 Antonio    3  null      null       Ahmed  Equipe Krishna   Pauli Yussuf Abed
 2  last_name String   100     81     0      A.    5  null      null 'Chincheta' 't Hoen      A. Aagaard    a'Hiller
 3     gender String   100      1     0       M  100  null      null           M       M       M       M           M

   id first_name          last_name gender
 0  2    Michael 'babeepower' Viera      M
 1  3       Eloy        'Chincheta'      M
 2  4   Dieguito        'El Cigala'      M
 3  5    Antonio   'El de Chipiona'      M
 4  6       José       'El Francés'      M
...

         name   type count unique nulls     top freq  mean       std  min   p25    median     p75      max
 0         id    Int   100    100     0       1    1 53,22 30,099022    1    27        54      80      104
 1 first_name String   100     97     0 Mohamed    3  null      null A.C.  Emil     Lauri Per (I)     Zaki
 2  last_name String   100     65     0  Abbott   15  null      null    1 Aaron Abashidze  Abbott a'Hiller

   id first_name   last_name
 0  1       Todd           1
 1  2        Les 12 Poissons
 2  3    Lejaren    a'Hiller
 3  4       Nian           A
 4  5   Khairiya   A-Mansour
...

          name   type count unique nulls   top freq      mean       std    min    p25 median    p75 max
 0 director_id    Int   100     41     0     8    8 35,340000 17,446148      2     22     37     52  61
 1       genre String   100     15     0 Drama   21      null      null Action Comedy  Drama Sci-Fi War
 2        prob  Float   100     27     0     1   40  0,623749  0,347447      0      0      1      1   1

   director_id       genre prob
 0           2       Short  1,0
 1           3       Drama  1,0
 2           5 Documentary  1,0
 3           6       Drama  1,0
 4           6       Short  1,0
...

   name   type count unique nulls           top freq        mean       std  min                      p25 median        p75         max
 0   id    Int   100    100     0             0    1   51,320000 30,230054    0                       24     52         78         103
 1 name String   100     98     0 $1,000 Reward    3        null      null  #28 $50,000 Climax Show, The    'A' 'Columbia' 'burbs, The
 2 year    Int   100     48     0          1901    9 1951,500000 41,555488 1897                     1912   1956       1994        2004
 3 rank Float?   100     22    74             7    2    6,150000  1,508178    3                        5      7          7          10

   id                                name year rank
 0  0                                 #28 2002 null
 1  1 #7 Train: An Immigrant Journey, The 2000 null
 2  2                                   $ 1971  6,4
 3  3                       $1,000 Reward 1913 null
 4  4                       $1,000 Reward 1915 null
...

          name type count unique nulls    top freq      mean           std  min           p25   median       p75    max
 0 director_id  Int   100     32     0      8   35     17,41     10,420546    1      8,000000     14,5     28,00     36
 1    movie_id  Int   100    100     0 378879    1 205821,36 113065,703491 1807 117759,583333 209978,0 287479,75 398143

   director_id movie_id
 0           1   378879
 1           2   281325
 2           3    30621
 3           3   304743
 4           4    60570
...

       name   type count unique nulls   top freq  mean       std    min    p25 median   p75     max
 0 movie_id    Int   100     62     0    50    4 39,46 23,171482      1     18     38    61      77
 1    genre String   100     19     0 Short   24  null      null Action Comedy  Drama Short Western

   movie_id       genre
 0        1 Documentary
 1        1       Short
 2        2      Comedy
 3        2       Crime
 4        5     Western
...

       name   type count unique nulls     top freq      mean           std min                           p25  median      p75        max
 0 actor_id    Int   100     38     0      38   17     26,84     10,861590   2                            18      28       36         41
 1 movie_id    Int   100     95     0   12148    3 212441,49 145821,411937 846                         59362  221481   351937     411721
 2     role String   100     50     0 Himself   19      null          null     Cuarto Cuadro Flamenco 'Taran Himself Reporter Victoriano

   actor_id movie_id             role
 0        2   280088           Stevie
 1        2   396232 Various/lyricist
 2        3   376687         Gitano 1
 3        4   336265        El Cigala
 4        5   135644          Himself
...

**Convert 10000 rows from _actors_ table to the dataframe**

In [6]:
val actorDf = DataFrame.readSqlTable(dbConfig, "actors", 10000)
actorDf

id,first_name,last_name,gender
2,Michael,'babeepower' Viera,M
3,Eloy,'Chincheta',M
4,Dieguito,'El Cigala',M
5,Antonio,'El de Chipiona',M
6,José,'El Francés',M
7,Félix,'El Gato',M
8,Marcial,'El Jalisco',M
9,José,'El Morito',M
10,Francisco,'El Niño de la Manola',M
11,Víctor,'El Payaso',M
12,Antonio,'El Pescaíto',M
13,Luis,'El Plojo',M
14,Janny,'el Portugues',M
15,Antonio,'El Rilete',M
16,Baltazar,'El Toro',M
17,Luis Roberto,'Formiga',M
18,Murray the,'K',M
19,Néstor,'Kick Boxer',M
20,Tony,'La Chispa',M
21,Pollino,'Romero',M

**Find top-20 the most popular actor names**

In [7]:
import org.jetbrains.kotlinx.dataframe.api.groupBy

val top20ManActorNames = actorDf
    .groupBy { first_name }
    .count()
    .sortByDesc("count")
    .take(20)
    
top20ManActorNames

first_name,count
David,80
John,74
Daniel,49
Peter,46
Robert,46
Michael,45
Antonio,42
Luis,41
Paul,40
José,39
Richard,38
A.,36
Carlos,35
Frank,34
Joe,34
Steve,33
Jorge,33
Roberto,33
Tony,32
James,30

In [8]:
val top20ManActorNamesPlot = top20ManActorNames.plot {
    bars {
         x(first_name) {
            scale = categorical()
        }
        y(count)
    }
 }
 
 top20ManActorNamesPlot

**Exploring the movies: trending rank by year depends on genre**

In [9]:
val sqlQuery = """
SELECT name, year, rank, genre
FROM movies
INNER JOIN movies_genres ON movies.id = movies_genres.movie_id
WHERE movies.rank > 0.0 and (movies_genres.genre = "Comedy" OR movies_genres.genre = "Horror")
"""

val ratedMoviesDf = DataFrame.readSqlQuery(dbConfig, sqlQuery)
ratedMoviesDf

name,year,rank,genre
$,1971,"6,400000",Comedy
"$1,000,000 Duck",1971,"5,000000",Comedy
$1000 a Touchdown,1939,"6,700000",Comedy
$30,1999,"7,500000",Comedy
"$40,000",1996,"9,600000",Comedy
"'?' Motorist, The",1906,"6,800000",Comedy
'A' gai waak,1983,"7,200000",Comedy
'A' gai waak juk jaap,1987,"7,200000",Comedy
'Babicky dobjejte presne!',1983,"5,600000",Horror
"'burbs, The",1989,"5,900000",Comedy
"'burbs, The",1989,"5,900000",Horror
'Crocodile' Dundee II,1988,"4,900000",Comedy
'E',1981,"7,900000",Comedy
"'High Sign', The",1921,"7,700000",Comedy
"'Hyp-Nut-Tist', The",1935,"6,100000",Comedy
'Java Madness' formerly titled 'Coffe...,1995,"6,600000",Comedy
"'J to tedy beru, sfe...!'",1977,"5,200000",Comedy
'Manos' the Hands of Fate,1966,"1,600000",Horror
'Ne gnstige Gelegenheit,1999,"4,600000",Comedy
'Neath Brooklyn Bridge,1942,"5,400000",Comedy

In [10]:
val olapCube = ratedMoviesDf
    .select { year and genre and rank }
    .groupBy { year and genre }
    .mean { rank named "meanRank" } 
    //.aggregate {  mean { rank } into "meanRank" } <-- alternative to the previous row
    .sortBy { year and genre }
    
olapCube

year,genre,meanRank
1892,Comedy,"5,100000"
1895,Comedy,"6,850000"
1896,Comedy,"3,550000"
1896,Horror,"4,250000"
1897,Comedy,"4,500000"
1898,Comedy,"4,620000"
1898,Horror,"3,200000"
1899,Comedy,"4,280000"
1899,Horror,"3,300000"
1900,Comedy,"4,612500"
1901,Comedy,"4,741667"
1902,Comedy,"4,366667"
1903,Comedy,"5,375000"
1904,Comedy,"4,953846"
1905,Comedy,"4,563636"
1906,Comedy,"6,066667"
1907,Comedy,"5,480000"
1908,Comedy,"5,416667"
1909,Comedy,"5,066667"
1909,Horror,"5,100000"

In [11]:
val genreRankTrends = olapCube.plot {
    line {
        x(year)
        y(meanRank)
        color(genre)
        width = 1.0
    }
}
genreRankTrends

**How are popular different genres in different years?**

In [12]:
val sqlQuery = """
SELECT name, year, genre
FROM movies
INNER JOIN movies_genres ON movies.id = movies_genres.movie_id
WHERE movies.year < 1940
"""

// The example of extension function usage
val moviesDf = dbConfig.readDataFrame(sqlQuery)
moviesDf

name,year,genre
"$1,000 Reward",1923,Western
"$10,000 Under a Pillow",1921,Animation
"$10,000 Under a Pillow",1921,Comedy
"$10,000 Under a Pillow",1921,Short
"$100,000",1915,Drama
$1000 a Touchdown,1939,Comedy
"$20,000 Carat, The",1913,Crime
"$20,000 Carat, The",1913,Drama
"$20,000 Carat, The",1913,Short
"$2500 Bride, The",1912,Drama
"$2500 Bride, The",1912,Romance
"$2500 Bride, The",1912,Short
"$5,000 Reward",1918,Mystery
"$5,000,000 Counterfeiting Plot, The",1914,Crime
"$5,000,000 Counterfeiting Plot, The",1914,Thriller
"$50,000 Jewel Theft, The",1915,Short
"$50,000 Reward",1924,Western
"$500 Reward, The",1911,Comedy
"$500 Reward, The",1911,Short
"$500,000 Reward",1911,Comedy

In [13]:
val aggregatedDF = moviesDf
    .select { year and genre }
    .groupBy { year and genre }
    .aggregate {  count()  into "count" }
    .sortBy { year and genre }
    
aggregatedDF

year,genre,count
1888,Short,2
1890,Short,3
1891,Short,2
1892,Animation,3
1892,Comedy,1
1892,Documentary,1
1892,Romance,1
1892,Short,4
1893,Short,1
1894,Comedy,1
1894,Documentary,16
1894,Drama,1
1894,Short,31
1895,Animation,1
1895,Comedy,4
1895,Documentary,27
1895,Drama,1
1895,Sci-Fi,1
1895,Short,44
1896,Comedy,21

In [15]:
val genreRankTrends = aggregatedDF.plot {
    points {
        x(year) // auto-generated df columns
        y(genre) {
            scale = categorical()
        }
        symbol = Symbol.CIRCLE_FILLED
        color = Color.BLUE
        fillColor(genre)
        size(count) {
            scale = continuous(1.0..30.0)
        }
    }
    layout.size = 1000 to 600
}

genreRankTrends

In [16]:
genreRankTrends.save("exported_plot.png")

C:\Users\Aleksey.Zinovev\IdeaProjects\KotlinDataFrame-SQL-Examples\notebooks\lets-plot-images\exported_plot.png

**Extracting data from the ResultSet with extension functions**

In [17]:
import org.jetbrains.kotlinx.dataframe.io.db.MariaDb

val props = Properties()
props.setProperty("user", USER_NAME)
props.setProperty("password", PASSWORD)

val TARANTINO_FILMS_SQL_QUERY = """
    SELECT name, year, rank,
    GROUP_CONCAT (genre) as "genres"
    FROM movies JOIN movies_directors ON movie_id = movies.id
    JOIN directors ON directors.id=director_id LEFT JOIN movies_genres ON movies.id = movies_genres.movie_id
    WHERE directors.first_name = "Quentin" AND directors.last_name = "Tarantino"
    GROUP BY name, year, rank
    ORDER BY year
    """

var dfTarantinoFilmsRs: DataFrame<*>

DriverManager.getConnection(URL, props).use { connection ->
    connection.createStatement().use { st ->
        st.executeQuery(TARANTINO_FILMS_SQL_QUERY).use { rs ->
            val dfTarantinoFilmsSchema = rs.readDataFrameSchema(MariaDb)
            dfTarantinoFilmsSchema.print()
            
            dfTarantinoFilmsRs = rs.readDataFrame(MariaDb)
            dfTarantinoFilmsRs
        }
    }
}

name: String?
year: Int?
rank: Float?
genres: String?

name,year,rank,genres
My Best Friend's Birthday,1987,"3,900000","Comedy,Drama"
Reservoir Dogs,1992,"8,300000","Crime,Mystery,Action,Thriller"
"""ER""",1994,null,null
Pulp Fiction,1994,"8,700000","Drama,Crime"
Four Rooms,1995,"5,900000","Comedy,Drama"
Jackie Brown,1997,"7,500000","Crime,Drama,Thriller"
"""Jimmy Kimmel Live""",2003,null,null
Kill Bill: Vol. 1,2003,"8,400000","Thriller,Action,Crime"
Kill Bill: Vol. 2,2004,"8,200000","Romance,Action,Thriller,Drama"
Inglorious Bastards,2006,null,"Drama,War,Action"

In [18]:
val df = dfTarantinoFilmsRs
    .fillNA { year }
    .with { 0 }
    .convert { year }.toInt()

In [19]:
df.filter { year > 2000 }

name,year,rank,genres
"""Jimmy Kimmel Live""",2003,null,null
Kill Bill: Vol. 1,2003,"8,400000","Thriller,Action,Crime"
Kill Bill: Vol. 2,2004,"8,200000","Romance,Action,Thriller,Drama"
Inglorious Bastards,2006,null,"Drama,War,Action"